### ISSUE TITLE
Update the supported Operating Systems for Beats

### ISSUE THREAD

**Issue by monicasarbu** [elastic/libbeat#213]
Here is the link https://www.elastic.co/support/matrix.
We should also make sure the init scripts work on each operating system.
I would say we support Windows Server 2012 or 2008, but it needs to be tested.

**Comment by tsg** [comment]
We test Windows 2012/R2 in our packaging tests, so that we can add already. I'd say it's fine to test 2008 only once manually and if it works mark it as supported.

**Comment by andrewkroh** [comment]
Does anyone know where this matrix is stored at?

**Comment by ruflin** [comment]
I'm sure @clintongormley knows here more.

**Comment by monicasarbu** [comment]
Haley Stephenson says there is a xsl sheet.

**Comment by monicasarbu** [comment]
@hstephenson Can you please send us the link to the xsl sheet?

**Comment by hstephenson** [comment]
@monicasarbu not a problem. Here's [**the Google Sheet that we're using to track updates in.**](https://docs.google.com/spreadsheets/d/10B1c0kFe0XrUu9lUwzUEr4XMeK_4ppao2KNzJp_Wp4M/edit#gid=1008171055) 

Note, since we don't really have track changes in sheets, please identify your updates/revisions by highlighting the appropriate cell(s) yellow. Looks like Tanya already started in on it, so feel free to add or ask questions!

**Comment by monicasarbu** [comment]
I added another check in the matrix, for Windows 2012/R2. @hstephenson I changed the matrix in the google doc. How can we update the matrix online? Thanks

**Comment by hstephenson** [comment]
@monicasarbu are these changes that need to go through right now? I want to make sure we give Sylvie direction on what updates should happen as soon as possible vs. the changes that should happen for GA later this month. 

We can always use different highlighting colors, if that helps.

**Comment by monicasarbu** [comment]
@hstephenson The change can be done immediately, when @sylvie777 has time for it. I am not sure what is the procedure. I used the yellow color, to notify what I have changed. I am sorry if I messed it up.
