### ISSUE TITLE
Fix ES bulk_size documentation 

### ISSUE THREAD

**Issue by andrewkroh** [elastic/libbeat#251]
The actual config option is [`bulk_size`](https://github.com/elastic/libbeat/blob/master/outputs/outputs.go#L31) not [`bulk_max_size`](https://www.elastic.co/guide/en/beats/libbeat/master/configuration.html#_bulk_max_size).

**Comment by monicasarbu** [comment]
@dedemorton can you please have a look at this one?

**Comment by dedemorton** [comment]
@andrewkroh Just to clarify: Are you wanting me to change the name of the following configuration option from bulk_max_size to bulk_size? https://www.elastic.co/guide/en/beats/libbeat/current/configuration.html#_bulk_max_size 

Has the name of this configuration option changed in the .yml files for the Beats? Just double-checking because the files that I downloaded last week still say bulk_max_size.

**Comment by andrewkroh** [comment]
@dede Good point, the configuration files are also wrong. I am thinking it is probably easier to just change the code to match the current docs and configuration files. So I am going to unassign you.

**Comment by monicasarbu** [comment]
LGTM
