### ISSUE TITLE
Beats Standardisation and Update Automation

### ISSUE THREAD

**Issue by ruflin** [elastic/libbeat#280]
Every beat has a set of files and dependencies in common. The goal of this document is to discuss two issues:

* What is the easiest way to start a new beat? Which files are needed?
* How can an existing beat kept up to date? How can we make it easy that a beat profits from the newest enhancements to libbeat and the tooling around?

# Create a New Beat
A new beat can be generated in two ways. Either an existing simple beat like topbeat is copied or a generator is used to created the basic required files.

The following is a list which all beats should have in common. At least part of these files should be identical across all beats.

* .editorconfig
* .gitattributes
* .gitignore
* .travis.yml
* beat/yourbeat.go
* CHANGELOG.md
* config/config.go
* docs/index.asciidoc
* etc/Xbeat.yml
* etc/fields.yml
* Godeps/.../libbeat/
* LICENSE
* main.go
* Makefile
* README.md
* pre commit hook

In addition there are scripts / libraries from libbeat which currently exist in all beats but could be reused:

* scripts/crosscompile.sh
* scripts/generate-*.py

A generator could be used to create the above files and fill them with the standard content based on the beat name.

# Updating Existing Beat
A bigger challenge is to update existing beats. As shown above, lots of files are shared and parts of these files are identical. A fix in the Makefile or an improvement in the .gitignore file can be beneficial for all beats, but at the same time every beat has its own additions. In case the libbeat base config is updated, all the depending beats must be updated. Updating Godeps only updates the go files.

To simplify this process and make it scalable, it should be automated.

# Proposed Solution

For the problem "create beat" I think the best solution is to clone an existing simple beat. But to do this is must be ensured that the beat is up-to-date with the most recent changes and can fetch new changes. This directly requires a solution for problem number two.

## Template Line

A differentiation must be made between the files which must be updated and the ones which only must be generated. README.md should never be overwritten, but .gitignore parts should be added if new ones exist in libbeat. All files which must be updated, should be split into two parts: beat specifics, libbeat details. To make it possible to use the "original" files but still make it modifyable, a standard "template" line should be introduced. For example the .gitignore file could look as following:

```
file.test
tmp

### libbeat generated - do not change ###

build
.vagrant
...
```

Then a script would be used to automatically replace everything after the headline with the most recent changes from libbeat if called.

The same would apply to all other files which would have to updated.

## Automatic Branch and Committing
These changes should not automatically be commited to master, but it would be nice to have a script that creates a branch, makes a commit, pushes the changes and opens a pull request for review. All these changes should always be still reviewed manually to make sure no errors happen.

## Problems

I think these scripts should "live" in libbeat, means somehow every beat must be able to fetch this script from libbeat and the run it. It could be that the fetching of the script is a generic command that should not change over time.

# References
* https://discuss.elastic.co/t/beats-starting-kit/33640/8

**Comment by ruflin** [comment]
@mrkschan @urso Have a look.

**Comment by tsg** [comment]
I see this related a bit with the discussion about moving to a single repository.  Assuming we make the change to a single repository, here is how I see things:

### Case 1:  a Beat is in the main repo

We need to make sure it conforms to all our standards regarding docs, code style, testing, review process, etc. But since it's a single repository, it's a lot easier to provide a common infrastructure for this. For example:
* all the dot files, the license file, copyright, contributing files, etc. will be common. 
* the fields.yml can be split between libbeat and the beats, and whatever scripts makes use of that can gather them all.
* libbeat will no longer be in godeps, and all beats from the main repo must be updated at once or the build fails
* we could have a common Makefile, or at least it will be easier to use common scripts from the individual Makefiles which can than become minimal

For the rest of the things in the list, like `main.go`, `README`, etc, they don't tend to change too often, so I think the problem is greatly reduced.

### Case 2: a Beat is not in the main repo

If a Beat is not in the main repo, than it is more of an independent project that uses libbeat. This means the Beat author doesn't necessarily  has to bother with documentation in asciidoc, providing `etc/fields.yml`, vendoring deps, etc. In a way, I think this actually lowers the entry barrier. Many cool Beats start as experiments, often by non-Golang programmers, and we can't expect them to keep up with libbeat changes, our review process, documentation requirements, testing requirements, etc. 

I imagine the normal process for a community Beat is that it starts independent, and if we and the author decide it would make sense for the project to move into the main repo, we ask for a pull request with all the code (so CLA is taken care of) and we put in the effort for docs, testing, etc. This is similar with the way the standard libraries of many programming languages adopt new libraries.

**Comment by mrkschan** [comment]
New beats
=========

* .editorconfig is a cool thing, though i'm not sure if everyone knows what is it.
* docs/index.asciidoc, not sure if that's good for community beats, since github supports wiki / a nice README.md
* etc/fields.yml, i'm okay with that since that can generate index template.
* Godeps, i'm not a fan of any golang dependency manager yet, though i'm fan of vendor mode available in golang 1.5 (which is not the case of official beats from Elastic right now).
* LICENSE, i think Elastic would have a legal team who can answer if it's a good idea to have a "default" license.
* Makefile, i'm not sure if all community beats would use coverage or other ci tools that official beats are using. A minimal one that include make, make test is good to start with.


Update beats
============

* Can we have `include xxx.yml` in the config? Inputs of beats are different. Outputs and logging parts would be similar across all beats though.
* I'm not sure if many files can really be updated automatically like .gitignore.


Branching
=========

* This is a great idea!


Generic script
==============

* If that's really the way to go, can we have something like ... `curl -sL https://raw.githubusercontent.com/.../beatskit.py | python -`

**Comment by ruflin** [comment]
I started some tests here in libbeat (https://github.com/elastic/libbeat/pull/284) and took filebeat as the first repo to experiment with (https://github.com/elastic/filebeat/pull/218). Still WIP. Currently the main target is to better automate the releases and be more consistent across all beats. Most parts here are independent of or multiple repos.

**Comment by ruflin** [comment]
This was implemented through the update.sh script: https://github.com/elastic/libbeat/blob/master/scripts/update.sh

**Comment by ruflin** [comment]
For a next step on this see: https://github.com/elastic/beats/pull/800
