### ISSUE TITLE
RabbitMQ output

### ISSUE THREAD

**Issue by derEremit** [elastic/libbeat#313]
If i'm not mistaken it's pretty common to use RabbitMQ as a buffer in an ELK stack.
So having rabbitmq output as a standard option in libBeat should make sense!

**Comment by derEremit** [comment]
sorry, I'm quite new to ELK stack, so I could be asking dumb questions.
regarding:
1) that's okay for filebeat, but what about topbeat for example.
2) is currently not really my main concern

what I think I heard last week during elasticON munich was that as logstash in not yet able to "cluster" one should currently use rabbit as security, for when the logstash instance goes down!

**Comment by timstoop** [comment]
We use RabbitMQ as a buffer and as a way to easily distribute messages to the processing logstashes. Logstash itself tends to require a lot more resources to be able to handle the datastream than a RabbitMQ, even when it's only configured to push messages towards a queue. RabbitMQ is in our opinion far better at handling sudden increases in events than logstash with the added benefit of being a buffer in case the logstashes can't handle the traffic by themselves. Scaling in another logstash or two to add processing power would then quickly empty the queues.

Another reason for us is so we can better manage resources between customers. We maintain servers for several customers, each with their own queue in RabbitMQ. The logstashes are setup to treat each queue equally, so a sudden increase in traffic for customer X does not necessarily cause a slowndown of the processing for customer Y as well. In logstash, we would have to open additional ports for doing this (as far as I know, at least). That's why we would like to have AMQP support for libbeat.

**Comment by adiworkoholic** [comment]
:+1: 
Show some love for the :rabbit2: ... they are cute :P

**Comment by monicasarbu** [comment]
This is the old repository of libbeat. Closing the issue in favor of https://github.com/elastic/beats/issues/581
